<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cassius</string>
	</array>
	<key>name</key>
	<string>Yesod Cassius</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.yesod</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.other.yesod</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([#@]){(.+)}</string>
			<key>name</key>
			<string>interpolation.yesod</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.indent.css</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.yesod.cassius</string>
	<key>uuid</key>
	<string>5664d328-5483-4e7d-b6c5-72d3e50b4179</string>
</dict>
</plist>
