<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>hamlet</string>
	</array>
	<key>name</key>
	<string>Yesod Hamlet</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>([_@#^]){</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>interpolation.yesod</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.haskell</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\$[a-z]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.other.yesod</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>inline.yesod</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.haskell</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.yesod.hamlet</string>
	<key>uuid</key>
	<string>6f5702a5-ff71-4e8f-a7dc-ec3ac750fd49</string>
</dict>
</plist>
