<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>msg</string>
	</array>
	<key>name</key>
	<string>Yesod message catalog</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^([A-Z][a-zA-Z0-9]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.other.yesod</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(:) </string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.yesod</string>
				</dict>
			</dict>
			<key>name</key>
			<string>message.yesod</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.haskell</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>([_@#^]){</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>interpolation.yesod</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.haskell</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.yesod.messages</string>
	<key>uuid</key>
	<string>1b7d40d2-6e3b-4ea9-a695-f8b768813b0b</string>
</dict>
</plist>
