<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>models</string>
	</array>
	<key>name</key>
	<string>Yesod models</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.haskell</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.yesod.models</string>
	<key>uuid</key>
	<string>593efacc-ab65-4cd6-baa0-a7807be5a89f</string>
</dict>
</plist>
