<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>routes</string>
	</array>
	<key>name</key>
	<string>Yesod routes</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^[/!]</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>meta.url.route.yesod</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[#*+]!?[A-Z][a-zA-Z0-9]+</string>
					<key>name</key>
					<string>support.type.patterns</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[A-Z][a-zA-Z0-9]+R</string>
					<key>name</key>
					<string>constant.other.handler</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(GET|HEAD|POST|PUT|DELETE|OPTIONS|PATCH)</string>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.yesod.routes</string>
	<key>uuid</key>
	<string>aaac8d25-bf96-4ecf-ad3b-46ea5315afe0</string>
</dict>
</plist>
